[build]
builder = "nixpacks"
buildCommand = "cd client && npm install && npm run build"

[deploy]
startCommand = "cd client && npx serve -s dist -l 8080"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 